services:
  sql:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: studentapp
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/01-init.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p1234 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 40s   # ðŸ”¥ VERY IMPORTANT

  backend:
    build:
      context: ./BE
    depends_on:
      sql:
        condition: service_healthy
    environment:
      DB_HOST: sql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: studentapp
    expose:
      - "8080"

  frontend:
    build:
      context: ./FE
    depends_on:
      - backend
    ports:
      - "8081:80"

volumes:
  mysql_data:
