services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: studentdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


  tomcat-backend:
    image: tomcat:10.1-jdk17
    container_name: tomcat-backend
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend:/usr/local/tomcat/webapps/student
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: studentdb
      DB_USER: student
      DB_PASSWORD: student123

  apache-frontend:
    image: httpd:2.4
    container_name: apache-frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/
    depends_on:
      - tomcat-backend

volumes:
  mysql_data:
